Fix compatibility with cartopy 0.20.0+
pytroll/pyresample pull request #378
Opened 2021-09-23 14:22 UTC by djhoese

Cartopy 0.20.0 includes updates by @snowman2 so that cartopy's CRS objects are now a subclass of pyproj's CRS class. Somehow this release broke compatibility with pyresample's hacky cartopy conversion where we started getting errors in our tests related to `towgs84` PROJ.4 string parameters being invalid. Something got lost in the CRS -> proj4 dict -> proj4 str -> CRS conversion.

Rather than figure out where this conversion issue was happening, I chose to implement something that I discussed in the cartopy issue here (https://github.com/SciTools/cartopy/issues/813). Instead of tricking cartopy into accepting arbitrary PROJ.4 information, this uses the new pyproj/cartopy CRS functionality to pass pyresample's pyproj CRS object directly to cartopy. This PR acts as a test for this functionality being added directly to cartopy (see referenced issue).

 - [ ] Tests added 
 - [x] Tests passed

2021-09-23 20:41 UTC, mraspaud requested changes
The changes lgtm, however, the new cartopy 0.20 isn't tested, right?

2021-09-23 23:47 UTC, djhoese commented
It is tested. That's how I knew that things weren't working (my other PRs were failing). This does not explicitly test older versions of cartopy, but I think given the improvements that are going on in cartopy we push users to update to newer cartopy as soon as possible. I'm not saying that old cartopy versions won't work with pyresample, but I would consider them on a short support cycle for the pyresample functionality. We can remove a lot of code from pyresample after my PR in cartopy gets merged and released.

Here's the conda log from one of the ubuntu jobs run here:

```
    + cartopy                              0.20.0  py38hc951a7f_0       conda-forge/linux-64       2 MB
```

Otherwise, you requested changes?

2021-09-24 05:33 UTC, mraspaud commented
OK, I don't understand the how you can test that both the new and old cartopy support is working without changing the tests more...

2021-09-24 15:40 UTC, djhoese commented
As described on slack, it isn't really possible to test both old and new cartopy. Eventually we want to deprecate old cartopy version support so we (@mraspaud and I) decided it would be easier to do it now. This PR now fixes support for 0.20.0+ but removes support for old versions. This cleans out a lot of old code. If my new cartopy PR gets merged and released then we could remove even more code from pyresample and just use cartopy directly.

2021-09-24 17:22 UTC, djhoese commented
@mraspaud I just found out from a student employee that the URL that cartopy uses for downloading shapefiles from NaturalEarth was updated for 0.20.0. The old one doesn't work any more. So forcing users to update to 0.20.0 doesn't sound so bad.

2021-09-30 06:10 UTC, mraspaud approved these changes
LGTM

2021-09-30 06:10 UTC, merged